Шаблонизируй это
htmlacademy-ecmascript/165513-cinemaddict-17 pull request #4
Opened 2022-05-19 10:56 UTC by ssnikiforov

2022-05-19 19:29 UTC, ant1quar requested changes

2022-05-19 19:29 UTC, ant1quar commented on src/view/popup-film-details-view.js
> +  } = film;
```suggestion
const popupFilmDetailsTemplate = ({ title, alternativeTitle, totalRating, poster, ageRating, director, writers, actors, release, runtime, genre, description }) => {
```

2022-05-19 19:29 UTC, ant1quar commented on src/view/popup-film-details-view.js
> +  const renderGenres = (genres) =>  genres.map((v) => `<span class="film-details__genre">${v}</span>`).join('');
Вставь этот однострочник прямо в темплейт

2022-05-19 19:29 UTC, ant1quar commented on src/utils.js
> +  return commentDateString;
```suggestion
  switch (true) {
    case diffTimeInDays > DayDiffs.THREE:
      return dayjs(commentDate).format('YYYY/MM/D H:m');
    case diffTimeInDays === DayDiffs.THREE:
      return `${DayDiffs.THREE} days ago`;
    case diffTimeInDays === DayDiffs.TWO:
      return `${DayDiffs.TWO} days ago`;
    case diffTimeInDays === DayDiffs.ONE:
      return `${DayDiffs.ONE} day ago`;
    case diffTimeInDays === DayDiffs.TODAY:
      return 'Today';
  }
```

2022-05-19 19:29 UTC, ant1quar commented on src/utils.js
> +  return commentDateString;
так чище. у тебя в utils еще одно место есть такое. надо фиксануть

2022-05-19 19:29 UTC, ant1quar commented on src/utils.js
> +const getProfileRatingName = (watchedFilmsCount) => {
тут тоже подчистить

2022-05-19 19:29 UTC, ant1quar commented on src/mock/comment.js
> +  return getRandomValuesFromArray(emojisValues, 1);
```suggestion
  return getRandomValuesFromArray(Object.values(Emojis), 1);
```

2022-05-19 19:29 UTC, ant1quar commented on src/mock/film.js
> +  ];
не очень хорошо генерить эту переменную на каждый вызов функции. засунь в const

2022-05-19 19:29 UTC, ant1quar commented on src/mock/film.js
> +  ];
и таких мест несколько

2022-05-20 06:51 UTC, ssnikiforov commented on src/view/popup-film-details-view.js
> +  } = film;
Done

2022-05-20 06:51 UTC, ssnikiforov commented on src/view/popup-film-details-view.js
> +  const renderGenres = (genres) =>  genres.map((v) => `<span class="film-details__genre">${v}</span>`).join('');
Done

2022-05-20 06:51 UTC, ssnikiforov commented on src/utils.js
> +  return commentDateString;
Done

2022-05-20 06:51 UTC, ssnikiforov commented on src/utils.js
> +const getProfileRatingName = (watchedFilmsCount) => {
Done

2022-05-20 06:51 UTC, ssnikiforov commented on src/mock/comment.js
> +  return getRandomValuesFromArray(emojisValues, 1);
Done

2022-05-20 06:51 UTC, ssnikiforov commented on src/mock/film.js
> +  ];
Done

2022-05-22 07:25 UTC, merged